#! /usr/bin/python3
# -*- coding: utf8 -*-
# The global setting file for nv-middlebox.

__author__ = "Sugesh Chandran"
__copyright__ = "Copyright (C) The neoview team."
__license__ = "GNU Lesser General Public License"
__version__ = "1.0"

import logging

#nv-middle-box common settings
NV_MID_BOX_APP_NAME = "nv-middle-box"
#Middle box camera streaming file Directory
NV_MID_BOX_CAM_STREAM_DIR = "/tmp/camera"

# The size of file generated by camera thread to be valid.
# Any file less than doesnt copy to the webserver
# Should be specified in MB.
NV_CAM_VALID_FILE_SIZE_MB = 4   # 4MB

# Camera connection timeout.
# The timeout period to consider a camera is dead. camera will be considered as
# disconnected when filesize < NV_CAM_VALID_FILE_SIZE_MB for a period of
# NV_CAM_CONN_TIMEOUT.
# The minimum timeout woule be atleast 5 min.
NV_CAM_CONN_TIMEOUT = 300  # 300 sec/5 min

# nv-middle-box logging Settings
NV_DEFAULT_LOG_LEVEL = logging.DEBUG
NV_LOG_FILE = "/tmp/nv_middlebox.log"
NV_LOG_FORMAT = "%(asctime)s - %(levelname)s - %(name)s - %(funcName)s - %(message)s"
# Set to 'True'/'False' to enable/disable console logging.By default its 'False'
NV_CONSOLE_LOG = False


#nv-middlebox db settings
#NVDB_SQLALCHEMY_DB = 'sqlite:///:memory:' #Inmemory DB

#NVDB_SQLALCHEMY_DB = 'sqlite:///nvdb.db' #Relative path db
NVDB_SQLALCHEMY_DB = 'sqlite:////tmp/nvdb.db' #absolute path db

#nv-middlebox database logging settings.
NVDB_DEFAULT_LOG_LEVEL = logging.DEBUG
#NVDB_LOG_FILE = "/usr/local/var/log/nv-middlebox/nvdb.log"
NVDB_LOG_FILE = "/tmp/nvdb.log"
NVDB_LOG_FORMAT = "%(asctime)s - %(levelname)s - %(message)s"

# MIDDLEBOX WEBSERVER SETTINGS.
## Middlebox http server port.
## DO NOT EXPOSE THIS PORT ON EXTERNAL NETWORK.
NV_MIDBOX_PAGE_HTTP_PORT=9000

## Middlebox https server port for websocket.
## All the external websocket connections(such as connection from stream web
## server) should be through this port.
## THIS PORT ONLY EXPOSED TO EXTERNAL NETWORK.
NV_MIDBOX_HTTPS_WS_PORT=8080

## Middlebox http server port for websocket.
## All the internal websocket connections(such as connection from switch page)
## should use this port for the communication. NEVER EXPOSE THIS PORT TO
## EXTERNAL NETWORK.
NV_MIDBOX_HTTP_WS_PORT=9090
